version: "3"
services:
  database:
    image: mysql
    restart: always
    container_name: test
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "3306:3306"